services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ttmobile
      POSTGRES_PASSWORD: ttmobile
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgres_data:
